excluded:
 - Pods

disabled_rules:
- trailing_whitespace
- multiple_closures_with_trailing_closure

opt_in_rules:
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters_brackets
  - multiline_arguments

identifier_name:
  excluded:
    - id
